/**
 * A synthetic construction sheet, generated with pdf-lib at runtime.
 *
 * Shipping a real drawing would mean shipping someone's copyrighted plan set, and shipping nothing
 * would leave the demo needing a file before it does anything. This draws an ARCH D sheet with a
 * title block, a grid, a room layout and a scale bar — enough to exercise calibration, measurement,
 * title-block extraction and the markup tools against something that behaves like a drawing.
 */
import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";

/** ARCH D, in points. */
const W = 36 * 72;
const H = 24 * 72;
/**
 * The plan is drawn at 1/8" = 1'-0", so one foot occupies 1/8 of a plotted inch — 72/8 = 9 points.
 * This has to be exactly right: the demo's whole point is that calibrating to the scale printed in
 * the title block yields the dimensions printed on the drawing.
 */
const PT_PER_FT = 72 / 8;

const INK = rgb(0.1, 0.1, 0.12);
const LIGHT = rgb(0.62, 0.64, 0.68);
const FAINT = rgb(0.82, 0.84, 0.86);

export async function makeSampleSheet(): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  drawPlanSheet(doc.addPage([W, H]), font, bold);
  drawDetailSheet(doc.addPage([W, H]), font, bold);
  // A spec page in the same file, so the specifications workspace and the search have real
  // CSI-formatted text to parse rather than needing a second upload.
  drawSpecSheet(doc.addPage([612, 792]), font, bold);

  doc.setTitle("A-201 — Second Floor Plan");
  doc.setSubject("Sample sheet generated by the Massing PDF demo");
  return doc.save();
}

function sheetFrame(page: PDFPage, font: PDFFont, bold: PDFFont, number: string, title: string, scale: string): void {
  const M = 36;
  const tbW = 200;

  // Border and title-block strip.
  page.drawRectangle({ x: M, y: M, width: W - M * 2, height: H - M * 2, borderColor: INK, borderWidth: 1.5 });
  page.drawLine({ start: { x: W - M - tbW, y: M }, end: { x: W - M - tbW, y: H - M }, color: INK, thickness: 1 });

  const tbX = W - M - tbW + 12;
  page.drawText("MASSING", { x: tbX, y: H - M - 30, size: 16, font: bold, color: INK });
  page.drawText("Sample Project — Adaptive Reuse", { x: tbX, y: H - M - 48, size: 8, font, color: LIGHT });
  page.drawText("123 Example Street", { x: tbX, y: H - M - 60, size: 8, font, color: LIGHT });

  // Title-block fields, bottom-up — this is the region the sheet extractor reads.
  page.drawText("SCALE", { x: tbX, y: M + 96, size: 6, font, color: LIGHT });
  page.drawText(scale, { x: tbX, y: M + 82, size: 10, font, color: INK });
  page.drawText("DATE", { x: tbX + 100, y: M + 96, size: 6, font, color: LIGHT });
  page.drawText("2026-07-26", { x: tbX + 100, y: M + 82, size: 10, font, color: INK });

  page.drawText("DRAWING TITLE", { x: tbX, y: M + 62, size: 6, font, color: LIGHT });
  page.drawText(title, { x: tbX, y: M + 46, size: 12, font: bold, color: INK });

  page.drawText("SHEET NUMBER", { x: tbX, y: M + 28, size: 6, font, color: LIGHT });
  page.drawText(number, { x: tbX, y: M + 8, size: 22, font: bold, color: INK });

  page.drawText("REV", { x: tbX + 140, y: M + 28, size: 6, font, color: LIGHT });
  page.drawText("C", { x: tbX + 140, y: M + 8, size: 22, font: bold, color: INK });
}

/** A graphic scale bar — the thing a reviewer calibrates against on a scanned sheet. */
function scaleBar(page: PDFPage, font: PDFFont, x: number, y: number): void {
  const seg = 20 * PT_PER_FT;                       // 20-foot divisions
  for (let i = 0; i < 4; i++) {
    page.drawRectangle({
      x: x + i * seg, y, width: seg, height: 5,
      color: i % 2 ? rgb(1, 1, 1) : INK, borderColor: INK, borderWidth: 0.5,
    });
    page.drawText(String(i * 20), { x: x + i * seg - 3, y: y - 9, size: 5, font, color: INK });
  }
  page.drawText("80", { x: x + 4 * seg - 5, y: y - 9, size: 5, font, color: INK });
  page.drawText(`GRAPHIC SCALE — FEET`, { x, y: y - 19, size: 5, font, color: LIGHT });
}

function drawPlanSheet(page: PDFPage, font: PDFFont, bold: PDFFont): void {
  sheetFrame(page, font, bold, "A-201", "SECOND FLOOR PLAN", `1/8" = 1'-0"`);

  const ox = 120, oy = 180;
  const ft = (n: number) => n * PT_PER_FT;

  // Column grid at 24 ft, with bubbles — the reference a coordination markup cites.
  const cols = 6, rows = 4, bay = 24;
  for (let c = 0; c <= cols; c++) {
    const x = ox + ft(c * bay);
    page.drawLine({ start: { x, y: oy - 14 }, end: { x, y: oy + ft(rows * bay) + 24 }, color: FAINT, thickness: 0.5, dashArray: [4, 3] });
    page.drawCircle({ x, y: oy + ft(rows * bay) + 34, size: 9, borderColor: INK, borderWidth: 0.8, color: rgb(1, 1, 1) });
    page.drawText(String.fromCharCode(65 + c), { x: x - 3, y: oy + ft(rows * bay) + 31, size: 8, font: bold, color: INK });
  }
  for (let r = 0; r <= rows; r++) {
    const y = oy + ft(r * bay);
    page.drawLine({ start: { x: ox - 24, y }, end: { x: ox + ft(cols * bay) + 14, y }, color: FAINT, thickness: 0.5, dashArray: [4, 3] });
    page.drawCircle({ x: ox - 34, y, size: 9, borderColor: INK, borderWidth: 0.8, color: rgb(1, 1, 1) });
    page.drawText(String(r + 1), { x: ox - 37, y: y - 3, size: 8, font: bold, color: INK });
  }

  // Exterior envelope: a double line, as a wall reads on a plan.
  const wallOuter = { x: ox, y: oy, w: ft(cols * bay), h: ft(rows * bay) };
  page.drawRectangle({ ...boxArgs(wallOuter), borderColor: INK, borderWidth: 1.6 });
  page.drawRectangle({
    x: wallOuter.x + 4, y: wallOuter.y + 4, width: wallOuter.w - 8, height: wallOuter.h - 8,
    borderColor: INK, borderWidth: 0.8,
  });

  // Rooms, each labelled and numbered the way a plan is.
  const rooms: [string, string, number, number, number, number][] = [
    ["OPEN OFFICE", "201", 0, 0, 72, 48],
    ["CONFERENCE", "202", 72, 0, 48, 24],
    ["BREAK ROOM", "203", 72, 24, 48, 24],
    ["CORRIDOR", "204", 0, 48, 120, 12],
    ["MECH / ELEC", "205", 120, 0, 24, 36],
    ["STORAGE", "206", 120, 36, 24, 24],
    ["STAIR", "207", 120, 60, 24, 36],
    ["RESTROOM", "208", 0, 60, 36, 36],
    ["HUDDLE", "209", 36, 60, 36, 36],
    ["LAB", "210", 72, 60, 48, 36],
  ];
  for (const [name, num, x, y, w, h] of rooms) {
    const box = { x: ox + ft(x), y: oy + ft(y), w: ft(w), h: ft(h) };
    page.drawRectangle({ ...boxArgs(box), borderColor: INK, borderWidth: 0.9 });
    const label = `${name}`;
    const size = 6;
    page.drawText(label, {
      x: box.x + box.w / 2 - font.widthOfTextAtSize(label, size) / 2,
      y: box.y + box.h / 2 + 2, size, font, color: INK,
    });
    page.drawText(num, {
      x: box.x + box.w / 2 - bold.widthOfTextAtSize(num, 7) / 2,
      y: box.y + box.h / 2 - 8, size: 7, font: bold, color: LIGHT,
    });
  }

  // An overall dimension string along the bottom, so a calibration has something to check against.
  const dimY = oy - 30;
  page.drawLine({ start: { x: ox, y: dimY }, end: { x: ox + ft(cols * bay), y: dimY }, color: INK, thickness: 0.6 });
  for (const x of [ox, ox + ft(cols * bay)]) {
    page.drawLine({ start: { x, y: dimY - 4 }, end: { x, y: dimY + 4 }, color: INK, thickness: 0.6 });
  }
  const dim = `144'-0"`;
  page.drawText(dim, {
    x: ox + ft(cols * bay) / 2 - font.widthOfTextAtSize(dim, 7) / 2,
    y: dimY + 5, size: 7, font, color: INK,
  });

  scaleBar(page, font, ox, oy - 62);

  page.drawText("NORTH", { x: ox + ft(cols * bay) - 40, y: oy - 62, size: 6, font: bold, color: INK });
  page.drawLine({
    start: { x: ox + ft(cols * bay) - 26, y: oy - 66 }, end: { x: ox + ft(cols * bay) - 26, y: oy - 40 },
    color: INK, thickness: 1,
  });

  page.drawText("KEYED NOTES", { x: 120, y: H - 90, size: 8, font: bold, color: INK });
  const notes = [
    "1.  VERIFY EXISTING SLAB DEPRESSION PRIOR TO FRAMING.",
    "2.  FIRESTOP ALL PENETRATIONS — SEE SPEC 07 84 00.",
    "3.  COORDINATE CEILING HEIGHT WITH MECHANICAL.",
  ];
  notes.forEach((n, i) => page.drawText(n, { x: 120, y: H - 104 - i * 11, size: 7, font, color: LIGHT }));
}

function drawDetailSheet(page: PDFPage, font: PDFFont, bold: PDFFont): void {
  sheetFrame(page, font, bold, "A-501", "WALL SECTIONS AND DETAILS", `1 1/2" = 1'-0"`);

  // Three detail bubbles with hatched assemblies — enough structure to mark up and measure.
  for (let i = 0; i < 3; i++) {
    const x = 140 + i * 460;
    const y = 300;
    page.drawCircle({ x: x + 60, y: y + 420, size: 16, borderColor: INK, borderWidth: 1, color: rgb(1, 1, 1) });
    page.drawText(`${i + 1}`, { x: x + 55, y: y + 414, size: 13, font: bold, color: INK });
    page.drawText("A-501", { x: x + 46, y: y + 400, size: 6, font, color: LIGHT });

    page.drawRectangle({ x, y, width: 120, height: 380, borderColor: INK, borderWidth: 1.2 });
    for (let h = 0; h < 38; h++) {
      page.drawLine({
        start: { x, y: y + h * 10 }, end: { x: x + 30, y: y + h * 10 + 10 },
        color: FAINT, thickness: 0.4,
      });
    }
    page.drawLine({ start: { x: x + 30, y }, end: { x: x + 30, y: y + 380 }, color: INK, thickness: 0.8 });
    page.drawLine({ start: { x: x + 90, y }, end: { x: x + 90, y: y + 380 }, color: INK, thickness: 0.8 });

    const labels = ["EXTERIOR FINISH", "AIR/VAPOUR BARRIER", "CONT. INSULATION", "GYPSUM BOARD"];
    labels.forEach((l, k) => {
      const ly = y + 340 - k * 26;
      page.drawLine({ start: { x: x + 120, y: ly }, end: { x: x + 160, y: ly }, color: LIGHT, thickness: 0.5 });
      page.drawText(l, { x: x + 164, y: ly - 3, size: 6, font, color: INK });
    });
  }
}

/** A US-letter spec page in CSI three-part format. */
function drawSpecSheet(page: PDFPage, font: PDFFont, bold: PDFFont): void {
  const M = 72;
  let y = 792 - M;
  const line = (text: string, opts: { bold?: boolean; indent?: number; size?: number } = {}) => {
    const size = opts.size ?? 10;
    page.drawText(text, {
      x: M + (opts.indent ?? 0), y, size,
      font: opts.bold ? bold : font, color: INK,
    });
    y -= size * 1.55;
  };
  const gap = (n = 6) => { y -= n; };

  line("SECTION 07 84 00 - FIRESTOPPING", { bold: true, size: 12 });
  gap(10);
  line("PART 1 - GENERAL", { bold: true });
  gap();
  line("1.1 SUMMARY", { bold: true });
  line("A. Section includes penetration firestopping of fire-resistance-rated construction.", { indent: 18, size: 9 });
  gap();
  line("1.2 SUBMITTALS", { bold: true });
  line("A. Product Data: For each type of product indicated.", { indent: 18, size: 9 });
  line("B. Shop Drawings: Submit for each firestop configuration.", { indent: 18, size: 9 });
  line("1. Include location and construction details of each penetration.", { indent: 36, size: 9 });
  line("2. Include listing agency designations and installation instructions.", { indent: 36, size: 9 });
  gap();
  line("1.3 QUALITY ASSURANCE", { bold: true });
  line("A. Installer Qualifications: A firm approved by the manufacturer.", { indent: 18, size: 9 });
  line("B. Testing Agency Qualifications: Qualified per ASTM E 2174 for field inspection.", { indent: 18, size: 9 });
  gap();
  line("1.4 WARRANTY", { bold: true });
  line("A. Provide a written warranty covering materials for two years from substantial completion.", { indent: 18, size: 9 });
  gap(10);
  line("PART 2 - PRODUCTS", { bold: true });
  gap();
  line("2.1 MATERIALS", { bold: true });
  line("A. Provide firestopping complying with UL 1479 and ASTM E 814.", { indent: 18, size: 9 });
  line("B. Sealants shall conform to the requirements of the listed assembly.", { indent: 18, size: 9 });
  gap(10);
  line("PART 3 - EXECUTION", { bold: true });
  gap();
  line("3.1 INSTALLATION", { bold: true });
  line("A. Install firestopping per manufacturer written instructions.", { indent: 18, size: 9 });
  line("B. Coordinate with the second floor plan on Sheet A-201 for penetration locations.", { indent: 18, size: 9 });
  gap();
  line("3.2 CLOSEOUT", { bold: true });
  line("A. Submit record documents identifying each firestop location as installed.", { indent: 18, size: 9 });

  page.drawText("07 84 00 - 1", { x: 612 - M - 60, y: M - 20, size: 8, font, color: LIGHT });
}

const boxArgs = (b: { x: number; y: number; w: number; h: number }) =>
  ({ x: b.x, y: b.y, width: b.w, height: b.h });
